import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import React from 'react'
//import "./styles.css";
import { Chrono } from "react-chrono";
import {timelineData} from "../utils/constants";
export default function AboutMe() {
  return (
    <>
      <Head>
        <title>About Me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Please give me &nbsp;
            <code className={styles.code}>
              3 minutes
            </code> 
            &nbsp; to impress you!
          </p>

          <div>
            <a
              href="/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <i>Back to Home</i>
            </a>
            <a
              href="/contacts"
              target="_blank"
              rel="noopener noreferrer"
            >
              <i>Contacts</i>
              <br></br>
              <Image
                src="/pics/linkedIn.png"
                alt="Bill YCH Logo"
                className={styles.vercelLogo}
                width={25}
                height={25}
                priority
              />
            </a>
          </div>
        </div>

        <div className='text-center'>
          <div className={styles.description}>
            <h1><b>About Me</b></h1>
          </div>
        </div>

        <div className={styles.container}>
          <div className={styles.row}>
            <div className={styles.col}>
              <div className={styles.row}>
                <Image
                  className={styles.logo}
                  src="/pics/selfy_2.jpeg"
                  alt="Next.js Logo"
                  width={448}
                  height={600}
                  priority
                />
              </div>
              <br></br>
              <div className={styles.rowCentered}>
                <a
                href="/cv_23Q4.pdf"
                target="_blank"
                rel="noopener noreferrer"
                >
                  <button type='button' className='btn btn-danger'><b>View My Resume for Software Engineer by Clicking Here!</b></button>
                </a>
              </div>
              <br></br>
              <div className={styles.rowCentered}>
                <a
                href="/cv_23Q4.pdf"
                target="_blank"
                rel="noopener noreferrer"
                >
                  <button type='button' className='btn btn-warning'><b>View My Resume for Data Scientist by Clicking Here!</b></button>
                </a>
              </div>

            </div>
            <div className={styles.col}>
              <h4>Messages for Recruiters/Hiring Managers/Professors</h4>
              <p className={styles.justifyText}> &nbsp; I am Yan-Cheng (Bill) Hsu, a Software Development Engineer with <br></br>specialized expertise in AI and machine learning, drawing from a robust <br></br>academic foundation with a Master’s degree from UC San Diego. At<br></br> Amazon’s Artificial General Intelligence Org, I have been instrumental in<br></br> engineering secure SageMaker solutions for complex LLM/VLM training, <br></br>showcasing my capacity to manage extensive datasets with heightened <br></br>security considerations.</p>
              <p> &nbsp; My tenure at Amazon Alexa Org exemplifies my ability to streamline<br></br> onboarding processes, achieving a remarkable 90% reduction in integration <br></br>time through secure backend innovations. This feat reflects my dedication to <br></br>operational excellence and cybersecurity in the development of <br></br> AI infrastructures.</p>
              <p> &nbsp; I have made significant strides in AI research, highlighted by my authorship<br></br> of a publication in the 'Sensors' journal, where I introduced an advanced <br></br>statistical feature selection algorithm for deep learning applications in <br></br>vital sign monitoring. Furthermore, my expertise in time series analysis <br></br>is showcased through my development of self-supervised time series<br></br> transformers, a work that I have presented at the IEEE APSIPA ASC 2023<br></br> conference. This pioneering research contributes to state-of-the-art<br></br> methodologies in unsupervised learning, propelling advancements in the <br></br>processing and analysis of temporal data.</p>
              <p> &nbsp; Seeking to leverage my full-stack development skills, cloud computing<br></br> proficiency, and innovative research background, I am poised to tackle <br></br>new challenges in AI, aiming to deliver solutions that seamlessly blend <br></br>technological sophistication with unwavering security and reliability.</p>
            </div>

          </div>
        </div>
        <br></br>
        <br></br>
        <div className='text-center'>
          <div className={styles.description}>
            <h1><b>Events of My Software Career</b></h1>
          </div>
        </div>

      <br></br>
      <br></br>
      <div style={{ width: "90%", height: "1000px" }}>
        <Chrono items={timelineData} 
        mode='VERTICAL_ALTERNATING'
        slideShow
        slideItemDuration={1500}
        slideShowType="reveal"
        theme={{
          primary: 'red',
          secondary: 'blue',
          cardBgColor: 'pink',
          titleColor: 'red',
          titleColorActive: 'red',
        }}
        mediaSettings={{ 
          align: 'right', 
        }}
        fontSizes={{
          cardSubtitle: '1rem',
          cardText: '0.8rem',
          cardTitle: '1.25rem',
          title: '1rem',
        }}
        />
      </div>


      </main>
    </>
  )
}
