import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import React from 'react'


export default function Contacts() {
  return (
    <>
      <Head>
        <title>Contacts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
          Contact Me! &nbsp;
            <code className={styles.code}>
              I am looking for an SDE/MLE role!
            </code> 
             
          </p>

          <div>
            <a
              href="/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <i>@2023 All right reserved by Bill YC Hsu</i>
              <br></br>
              <Image
                src="/pics/logo.png"
                alt="Bill YCH Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className='text-center'>
          <div className={styles.description}>
            <h1><b>Contacts</b></h1>
          </div>
        </div>
        
        <div className={styles.container}>
          <div className={styles.row}>
          <div className={styles.col}>
              <a
                  href="bill.ych.jobs@gmail.com"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  
                  <Image
                    src="/pics/gmail_icon.png"
                    alt="publication_system_overview.png"
                    className={styles.vercelLogo}
                    width={200}
                    height={200}
                    priority
                  />
                  <br></br>
                  <div className='text-center'>bill.ych.jobs@gmai.com</div>
                  
                </a>
            </div>
            <div className={styles.col}>
              <a
                  href="https://www.linkedin.com/in/yan-cheng-hsu/"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Image
                    src="/pics/linkedIn.png"
                    alt="publication_system_overview.png"
                    className={styles.vercelLogo}
                    width={200}
                    height={200}
                    priority
                  />
                </a>
            </div>
            <div className={styles.col}>
              <a
                  href="https://github.com/Yan-Cheng-Hsu"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Image
                    src="/pics/github.png"
                    alt="publication_system_overview.png"
                    className={styles.vercelLogo}
                    width={200}
                    height={200}
                    priority
                  />
                </a>
            </div>
            <div className={styles.col}>
              <a
                  href="https://scholar.google.com/citations?hl=en&view_op=list_works&authuser=3&gmla=ABEO0YpeaGnjZtx4Np6ytz2FIHOnLAf2IPB0umyXRNAgxAeOx0jSMAQT6oBHzcAba2gn4k3CW4wvev2-8l7Amg&user=u0mWcuJySogC"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Image
                    src="/pics/googlescholar_icon.png"
                    alt="publication_system_overview.png"
                    className={styles.vercelLogo}
                    width={200}
                    height={200}
                    priority
                  />
                </a>
            </div>
            <div className={styles.col}>
              <a
                  href="https://www.instagram.com/bill.yc.hsu/"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Image
                    src="/pics/instagram_icon.png"
                    alt="publication_system_overview.png"
                    className={styles.vercelLogo}
                    width={200}
                    height={200}
                    priority
                  />
                </a>
            </div>
          </div>  
        </div>



      </main>
    </>
  )
}
