import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import React from 'react'
//import "./styles.css";

export default function Projects() {
  return (
    <>
      <Head>
        <title>Software Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Contact Me! &nbsp;
            <code className={styles.code}>
              I am looking for an SDE/MLE role!
            </code> 
          </p>
          <div>
            <a
              href="/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <i>Back to Home</i>
            </a>
            <a
              href="/contacts"
              target="_blank"
              rel="noopener noreferrer"
            >
              <i>Contacts</i>
              <br></br>
              <Image
                src="/pics/linkedIn.png"
                alt="Bill YCH Logo"
                className={styles.vercelLogo}
                width={25}
                height={25}
                priority
              />
            </a>
          </div>
        </div>

      <br></br>
      <br></br>
        <div className='text-center'>
            <div className={styles.description}>
              <h1><b>Software Projects</b></h1>
            </div>
        </div>

      <div className={styles.container}>
      <div className={styles.row}>
            <div className={styles.col}>
              <a
                href="/pics/personal_webv1v2.png"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  src="/pics/personal_webv1v2.png"
                  alt="sstd.png"
                  className={styles.vercelLogo}
                  width={550}
                  height={450}
                  priority
                />
              </a>
            </div>
            <div className={styles.col}>
                <a 
                  href="/pics/personal_webv1v2.png"
                >
                  <h3>My Personal Websites from Scratch</h3>
                </a>
                  <ul>
                    <li><b>Deployed a Next.js application on Azure VM</b>, secured with HTTPS <br></br>through Nginx, Certbot, and Azure
                        DNS configuration.</li>
                    <li>Implemented <b>Nginx reverse proxy</b> with Certbot for directing 8080 <br></br>port traffic to HTTPS.</li>
                    <li>Incorporated dynamic descriptions with typing and shining <br></br>animations and developed reusable components.</li>
                  </ul>
                <h6><b>Motivation</b>: 
                  Self-motivated
                </h6>
                <h6><b>Incumbency</b>:
                    &nbsp; Apr. 2023
                </h6>
                <a
                  href="https://github.com/Yan-Cheng-Hsu/dynamic_website"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Image
                    src="/pics/github.png"
                    alt="publication_system_overview.png"
                    className={styles.vercelLogo}
                    width={25}
                    height={25}
                    priority
                  />
                  <i>[ <u>Github</u> ]</i>

                </a>
            </div>
          </div>
      <br></br>
      <div className={styles.row}>
      <div className={styles.col}>
              <a
                href="/pics/raft.png"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  src="/pics/raft.png"
                  alt="sstd.png"
                  className={styles.vercelLogo}
                  width={550}
                  height={450}
                  priority
                />
              </a>
            </div>
            <div className={styles.col}>
                <a 
                  href='/pics/raft.png'
                >
                  <h3><b>Webserver && File Sharing System <br></br>from Scratch</b></h3>
                </a>
                  
                  <ul>
                    <li><b>Developed a concurrent web server using multi-threading</b>, <br></br>equipped with an HTTP/1.1 protocol handler
                        for request parsing <br></br>and response formulation.</li>
                    <li><b>Created a race-condition-free file sharing system with Meta <br></br>and Block Services</b>, supporting
                        simultaneous file synchronization <br></br>from multiple clients.</li>
                    <li>Incorporated the RAFT protocol to ensure system fault tolerance.</li>
                  </ul>
                <h6><b>Motivation</b>: 
                  UC San Diego CSE224 Course
                </h6>
                <h6><b>Incumbency</b>:
                    &nbsp; Jan. 2022
                </h6>
                <a
                  href="https://github.com/Yan-Cheng-Hsu/Webserver-File-Sharing-System"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Image
                    src="/pics/github.png"
                    alt="publication_system_overview.png"
                    className={styles.vercelLogo}
                    width={25}
                    height={25}
                    priority
                  />
                  <i>[ <u>Github</u> ]</i>

                </a>
            </div>

          </div>
          <br></br>
          <div className={styles.row}>
      <div className={styles.col}>
              <a
                href="/pics/db.png"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  src="/pics/db.png"
                  alt="sstd.png"
                  className={styles.vercelLogo}
                  width={550}
                  height={450}
                  priority
                />
              </a>
            </div>
            <div className={styles.col}>
                <a 
                  href='/pics/db.png'
                >
                  <h3><b>Buffer Manager and B+ Tree Indexing<br></br>System from Scratch</b></h3>
                </a>
                  
                  <ul>
                    <li><b>Implemented a B+ Tree file indexing system</b> for efficient <br></br>database operations including insertion, deletion,
                        node splits, and <br></br>range searches.</li>
                    <li>Developed a Buffer Manager utilizing the Clock Algorithm for <br></br>optimized buffer replacement.</li>
                  </ul>
                <h6><b>Motivation</b>: 
                  UC San Diego CSE132C Course
                </h6>
                <h6><b>Incumbency</b>:
                    &nbsp; Apr. 2022
                </h6>
                <a
                  href="https://github.com/Yan-Cheng-Hsu/Buffer-Manager-and-B-Tree-Indexing-System-from-Scratch-"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Image
                    src="/pics/github.png"
                    alt="publication_system_overview.png"
                    className={styles.vercelLogo}
                    width={25}
                    height={25}
                    priority
                  />
                  <i>[ <u>Github</u> ]</i>

                </a>
            </div>

          </div>
          <br></br>

          <div className={styles.row}>
      <div className={styles.col}>
              <a
                href="/pics/latent_factor_model.png"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  src="/pics/latent_factor_model.png"
                  alt="sstd.png"
                  className={styles.vercelLogo}
                  width={550}
                  height={450}
                  priority
                />
              </a>
            </div>
            <div className={styles.col}>
                <a 
                  href='/pics/latent_factor_model.png'
                >
                  <h3><b>Recommender System Rating Prediction</b></h3>
                </a>
                  
                  <ul>
                    <li>Designed a latent factor rating prediction model using TensorFlow, <br></br><b>securing a top 5% performance</b>
                        ranking in class.</li>
                    <li><b>Enhanced the model by integrating it with a deep residual network,</b> <br></br>resulting in a Mean Square Error
                        (MSE) of 0.83 over 500,000 shopping <br></br>records.</li>
                  </ul>
                <h6><b>Motivation</b>: 
                  UC San Diego CSE258 Course
                </h6>
                <h6><b>Incumbency</b>:
                    &nbsp; Dec. 2021
                </h6>
            </div>

          </div>
          <br></br>
          <div className={styles.row}>
            <div className={styles.col}>
              <a
                href="/pics/nms.png"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  src="/pics/nms.png"
                  alt="sstd.png"
                  className={styles.vercelLogo}
                  width={550}
                  height={450}
                  priority
                />
              </a>
            </div>

            <div className={styles.col}>
              <a
                href="/pics/epipolar1.png"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  src="/pics/epipolar1.png"
                  alt="publication_system_overview.png"
                  className={styles.vercelLogo}
                  width={550}
                  height={450}
                  priority
                />
              </a>
            </div>
          </div>
          <br></br>
          <div className={styles.row}>
            <div className={styles.col}>
              <a
                href="/pics/optical_flow.png"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  src="/pics/optical_flow.png"
                  alt="sstd.png"
                  className={styles.vercelLogo}
                  width={550}
                  height={450}
                  priority
                />
              </a>
            </div>
            <div className={styles.col}>
                <a 
                  href="/pics/optical_flow.png"
                >
                  <h3><b>Computer Vision Projects</b></h3>
                </a>
                  <ul>
                    <li><b>Developed edge and corner detection algorithms, utilizing <br></br>Non-maximum Suppression and
                        Hypothesising techniques.</b></li>
                    <li>Constructed partially and completely bounded camera <br></br>rectification solutions using epipolar geometry.</li>
                    <li><b>Designed a SIFT feature matching system leveraging <br></br>fundamental metrics computed with epipolar
                        geometry <br></br>and RANSAC.</b></li>
                    <li>Employed CNN-Dense classifiers in pattern recognition projects, <br></br>achieving 98% accuracy.</li>
                  </ul>
                <h6><b>Motivation</b>: 
                  UC San Diego CSE252A Course
                </h6>
                <h6><b>Incumbency</b>:
                    &nbsp; Dec. 2021
                </h6>
                <a
                  href="https://github.com/Yan-Cheng-Hsu/Computer-Vision-.git"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Image
                    src="/pics/github.png"
                    alt="publication_system_overview.png"
                    className={styles.vercelLogo}
                    width={25}
                    height={25}
                    priority
                  />
                  <i>[ <u>Github</u> ]</i>

                </a>
            </div>
          </div>

      </div>


      </main>
    </>
  )
}
