import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import React from 'react'
//import "./styles.css";

export default function WorkEXP() {
  return (
    <>
      <Head>
        <title>Work Experience</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Contact Me! &nbsp;
              <code className={styles.code}>
                I am looking for an SDE/MLE role!
              </code> 
          </p>
          <div>
            <a
              href="/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <i>Back to Home</i>
            </a>
            <a
              href="/contacts"
              target="_blank"
              rel="noopener noreferrer"
            >
              <i>Contacts</i>
              <br></br>
              <Image
                src="/pics/linkedIn.png"
                alt="Bill YCH Logo"
                className={styles.vercelLogo}
                width={25}
                height={25}
                priority
              />
            </a>
          </div>
        </div>

        <div className='text-center'>
          <div className={styles.description}>
            <h1><b>Publications</b></h1>
          </div>
        </div>

        <div className={styles.container}>
          <div className={styles.row}>
            <div className={styles.col}>
              <a
                href="pics/publication_system_overview.png"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  src="/pics/publication_system_overview.png"
                  alt="publication_system_overview.png"
                  className={styles.vercelLogo}
                  width={550}
                  height={450}
                  priority
                />
              </a>
            </div>
            <div className={styles.col}>
              <a
                href="/pics/ppg_algo.png"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  src="/pics/ppg_algo.png"
                  alt="ppg_algo.png"
                  className={styles.vercelLogo}
                  width={550}
                  height={450}
                  priority
                />
              </a>
            </div>
          </div>
          <br></br>
          <div className={styles.row}>
            <div className={styles.col}>
              <a
                href="/pics/ppg.png"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  src="/pics/ppg.png"
                  alt="publication_system_overview.png"
                  className={styles.vercelLogo}
                  width={550}
                  height={450}
                  priority
                />
              </a>
            </div>
            <div className={styles.col}>
                <a 
                  href="https://www.mdpi.com/1424-8220/20/19/5668"
                >
                  <h3><b>Generalized Deep Neural Network Model <br></br>for Cuffless Blood Pressure Estimation <br></br>with Photoplethysmogram Signal Only</b></h3>
                </a>
                <h6><b>Hsu, Yan-Cheng</b>; Li, Yung-Hui; Chang, Ching-Chun; Harfiya, Latifa N. <br></br><b><i>Sensors 20</i></b>,no. 19: 5668.</h6>
                  <ul>
                    <li>I developed a <b>deep-neural-network model for estimating blood <br></br>pressure</b>, innovatively integrating a statistical method for feature <br></br>selection. This enhanced the value of features extracted from <br></br>Photoplethysmography (PPG) signals.</li>
                    <li>The proposed model attained <b>cutting-edge performance</b> in 2020, <br></br>satisfying both the Association for the Advancement of Medical <br></br>Instrumentation (AAMI) and the British Hypertension Society (BHS) <br></br>standards for blood pressure measurement devices.</li>
                  </ul>
                <a
                  href="https://github.com/Yan-Cheng-Hsu/Blood-Pressure-Estimation-Model"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Image
                    src="/pics/github.png"
                    alt="publication_system_overview.png"
                    className={styles.vercelLogo}
                    width={25}
                    height={25}
                    priority
                  />
                  <i>[ <u>Github</u> ]</i>

                </a>

                
            </div>
          </div>

          <br></br>
          <div className={styles.row}>
            <div className={styles.col}>
              <a
                href="/pics/tst_so.png"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  src="/pics/tst_so.png"
                  alt="publication_system_overview.png"
                  className={styles.vercelLogo}
                  width={550}
                  height={450}
                  priority
                />
              </a>
            </div>
            <div className={styles.col}>
                <a 
                  href="https://ieeexplore.ieee.org/document/10317578"
                >
                <h3><b>On the Optimal Self-Supervised <br></br>Multi-Fault Detector for Temperature <br></br>Sensor Data</b></h3>
                </a>
                <h6>Latifa N.; <b>Hsu, Yan-Cheng</b>; Li, Y.H.; Wang, J.C. <br></br><i>APSIPA ASC 2023</i> <b>(Oral Presentation)</b></h6>
                  <ul>
                    <li>Implemented Developed self-supervised time series transformers,  <br></br>securing state-of-the-art performance on diverse temporal datasets.</li>
                    <li>Presented findings orally at the IEEE APSIPA ASC 2023 conference,  <br></br>highlighting innovative approaches in time series analysis.</li>
                  </ul>

                
            </div>
          </div>

          
      </div>
      <br></br>
      <br></br>
        <div className='text-center'>
            <div className={styles.description}>
              <h1><b>Work Experience</b></h1>
            </div>
        </div>

      <div className={styles.container}>
      <div className={styles.row}>
            <div className={styles.col}>
              <a
                href="/pics/confidential.png"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  src="/pics/confidential.png"
                  alt="sstd.png"
                  className={styles.vercelLogo}
                  width={550}
                  height={450}
                  priority
                />
              </a>
            </div>
            <div className={styles.col}>
                <a 
                  href="/pics/confidential.png"
                >
                  <h3><b>Project I: Olympus Models: Large <br></br>Language/Visual Models (LLM/LVM) <br></br>Tooling and Training Optimization on <br></br>Neurons</b></h3>
                </a>
                  <ul>
                    <li>Designed and delivered secure SageMaker solutions for AGI <br></br>scientists, facilitating the training of LLM/LVMs with 10B+ <br></br>parameters using over 1TB of data. Optimized processes with <br></br>pre-compilation, caching, and distributed training capabilities.</li>
                  </ul>
                  <a 
                  href="/pics/confidential.png"
                >
                  <h3><b>Project I: Nova Commands & <br></br>Hoverboard Environment: Sensai <br></br>Secure AI Platform</b></h3>
                </a>
                  <ul>
                    <li>Contributed to the understanding, maintenance, and <br></br>development of authorization and authentication systems for <br></br>the ML platform, reinforcing data security for AGI projects and<br></br> ensuring the safe handling of large datasets.</li>
                  </ul>
                  <h6><b>Company</b>: 
                  <a
                    href="https://www.amazon.com/"
                  >
                    &nbsp; Amazon.com LLC
                  </a>
                </h6>
                <h6><b>Organization</b>: 
                  <a
                    href="https://www.amazon.com/b?node=21576558011"
                  >
                    &nbsp; Artificial General Intelligence Org - Secure A.I. Foundatoins
                  </a>
                </h6>
                <h6><b>Position</b>:
                    &nbsp; Software Dev Engineer
                </h6>
                <h6><b>Incumbency</b>:
                    &nbsp; Oct. 2023 - present
                </h6>
            </div>
          </div>
      <br></br>
      <div className={styles.row}>
            <div className={styles.col}>
              <a
                href="/pics/comcom_system_overview.png"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  src="/pics/comcom_system_overview.png"
                  alt="sstd.png"
                  className={styles.vercelLogo}
                  width={550}
                  height={450}
                  priority
                />
              </a>
            </div>
            <div className={styles.col}>
                <a 
                  href="/pics/comcom_system_overview.png"
                >
                  <h3><b>Comcom Website: Command Line Tools <br></br>on The Web</b></h3>
                </a>
                  <ul>
                    <li><b>Developed, packaged, and deployed a decoupled web application <br></br>on AWS EC2, using Linux shell scripts and Docker images.</b> This <br></br>platform facilitates online code execution and sharing across various
                        <br></br>languages, eliminating the need for local package installations.</li>
                    <li>Built a <b>multi-threaded backend</b> with a SQL database and <b>file-sharing <br></br>system, capable of managing race
                        conditions, using Flask and Django</b> <br></br>and created <b>RESTful APIs</b> for request handling.</li>
                    <li>Built the frontend with React.js and Node.js, integrating event, state, <br></br>and proxy management.</li>
                  </ul>
                <h6><b>Company</b>: 
                  <a
                    href="https://ucsd.edu/"
                  >
                    &nbsp; University of California San Diego
                  </a>
                </h6>
                <h6><b>Organization</b>: 
                  <a
                    href="https://cse.ucsd.edu/"
                  >
                    &nbsp; Computer Science Department
                  </a>
                </h6>
                <h6><b>Position</b>:
                    &nbsp; Full-Stack Developer
                </h6>
                <h6><b>Incumbency</b>:
                    &nbsp; Feb. 2023 - present
                </h6>
                <a
                  href="https://github.com/Yan-Cheng-Hsu/ComCom-Project"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Image
                    src="/pics/github.png"
                    alt="publication_system_overview.png"
                    className={styles.vercelLogo}
                    width={25}
                    height={25}
                    priority
                  />
                  <i>[ <u>Github</u> ]</i>

                </a>
            </div>
          </div>
      <br></br>
      <div className={styles.row}>
            <div className={styles.col}>
              <a
                href="/pics/confidential.png"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  src="/pics/confidential.png"
                  alt="sstd.png"
                  className={styles.vercelLogo}
                  width={550}
                  height={450}
                  priority
                />
              </a>
            </div>
            <div className={styles.col}>
                <a 
                  href="/pics/confidential.png"
                >
                  <h3><b>Alexa Secure AI Platform: Sensai <br></br>Self-Service Onboarding Platform <br></br></b></h3>
                </a>
                  <ul>
                    <li><b>Created and launched a decoupled web application on<br></br> AWS Lambda and Cloudfront.</b> The platform
                        facilitates secure<br></br> onboarding of apps and APIs for scientists on the Sensai Platform.</li>
                    <li>Developed modules in backend such as <b>Auto-Verification <br></br>(which transfer various encrypted identifications via cookies and<br></br> session data), Canaries, Access Control, and Monitoring</b> using <br></br>AWS-CDK and AWS-SDK and streamlined the onboarding process <br></br>for the Alexa Org team, reducing app/API
                        integration time <br></br>from 4 hours to 15 minutes - <b>a 90% reduction.</b></li>
                    <li>Refined the existing webUI to augment the self-service capabilities<br></br> of the onboarding system.</li>
                  </ul>
                <h6><b>Company</b>: 
                  <a
                    href="https://www.amazon.com/"
                  >
                    &nbsp; Amazon.com LLC
                  </a>
                </h6>
                <h6><b>Organization</b>: 
                  <a
                    href="https://www.amazon.com/b?node=21576558011"
                  >
                    &nbsp; Alexa Org
                  </a>
                </h6>
                <h6><b>Position</b>:
                    &nbsp; Software Dev Engineer Intern
                </h6>
                <h6><b>Incumbency</b>:
                    &nbsp; Jun. 2022 - Sep. 2022
                </h6>
                <a
                  href="https://docs.google.com/presentation/d/1_oidZd77JGTxUhrUZbamzEXAbyRdB28j/edit?usp=sharing&ouid=116280290103505291852&rtpof=true&sd=true"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <i>[ <u>pptx</u> ]</i>

                </a>
            </div>
          </div>
          <br></br>
          <div className={styles.row}>
            <div className={styles.col}>
              <a
                href="/pics/wiwynn_systemoverview.png"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  src="/pics/wiwynn_systemoverview.png"
                  alt="sstd.png"
                  className={styles.vercelLogo}
                  width={550}
                  height={450}
                  priority
                />
              </a>
            </div>

            <div className={styles.col}>
                <a 
                  href="/pics/wiwynn_systemoverview.png"
                >
                  <h3><b>Prometheus Infrastructure Testing Data <br></br>Analysis and Software Toolkit <br></br>Development</b></h3>
                </a>
                  <ul>
                    <li>Established a prototype data pipeline for production line testing <br></br>data analysis.</li>
                    <li><b>Developed three comprehensive Python packages</b> for efficient <br></br>data collection, alignment, and analysis from various sources including <br></br>temporal infrastructure's hardware data (Prometheus) and production <br></br>line
                        testing databases.</li>
                    <li>Streamlined the scope of <b>production line performance enhancement <br></br>by approximately 66%</b> through
                        effective information filtering and <br></br>dimensionality reduction.</li>
                  </ul>
                <h6><b>Company</b>: 
                  <a
                    href="https://www.wiwynn.com/"
                  >
                    &nbsp; Wiwynn Inc(Acer's Child Company)
                  </a>
                </h6>
                <h6><b>Position</b>:
                    &nbsp; Software Dev Engineer Intern
                </h6>
                <h6><b>Incumbency</b>:
                    &nbsp; Jul 2021 - Aug 2021
                </h6>
            </div>
          </div>
          <br></br>
          <div className={styles.row}>
            <div className={styles.col}>
              <a
                href="/pics/publication_system_overview.png"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  src="/pics/publication_system_overview.png"
                  alt="sstd.png"
                  className={styles.vercelLogo}
                  width={550}
                  height={450}
                  priority
                />
              </a>
            </div>
            <div className={styles.col}>
                <a 
                  href="/pics/publication_system_overview.png"
                >
                  <h3><b>Deep Neural Network Predictor by <br></br>Introducing a new Feature Selection <br></br>Algorithm</b></h3>
                </a>
                  <ul>
                    <li>Designed and implemented a deep learning model for blood <br></br>pressure estimation, incorporating data
                        preprocessing, neural<br></br> network selection, and a novel physiological feature selection <br></br>algorithm.</li>
                    <li>Enhanced accuracy by ~1.8x and expanded data incorporation <br></br>by ~6x compared to the predecessor model, achieving a Mean<br></br> Absolute Error (MAE) of 2.73 mmHg across 2.5M+ cardiac cycles <br></br>from 9000
                        patients.</li>
                    <li>Published this groundbreaking work in the international journal, <br></br>Sensors 20.</li>
                  </ul>
                <h6><b>Company</b>: 
                  <a
                    href="https://www.honhai.com/en-us/rd-and-technology/institute"
                  >
                    &nbsp; Machine Learning and Biometric Recognition Lab
                  </a>
                </h6>
                <h6><b>Organization</b>: 
                  <a
                    href="https://en.csie.ncu.edu.tw/"
                  >
                    &nbsp; National Central University
                  </a>
                </h6>
                <h6><b>Position</b>:
                    &nbsp; Deep Learning Research Assistant
                </h6>
                <h6><b>Incumbency</b>:
                    &nbsp; Dec. 2020 - Oct. 2021
                </h6>
                <a
                  href="https://github.com/Yan-Cheng-Hsu/Blood-Pressure-Estimation-Model"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Image
                    src="/pics/github.png"
                    alt="publication_system_overview.png"
                    className={styles.vercelLogo}
                    width={25}
                    height={25}
                    priority
                  />
                  <i>[ <u>Github</u> ]</i>

                </a>
            </div>
          </div>

      </div>


      </main>
    </>
  )
}
